NAME = senha_corrigido

SRCS = main.c \
       senha_corrigido.c

all: 
	
#compilar objetos

#juntar objetos (executavel)
$(NAME): $(SRCS)
	gcc $(SRCS) -o $(NAME) 

#apagar objetos
#clean:

#apagar objetos e executavel
fclean:
	rm -rf $(NAME)

#recompilar
re: fclean all
	
