#ifndef GERADOR_H
#define GERADOR_H

// DEFINIR E ALTERAR SEMENTE
// QUANTOS NUMEROS GERADOS
// ÚLTIMO NÚMERO GERADO
// PRODUZIR NUMEROS ALEATORIOS EM VARIOS FORMATOS
// VALORES MÁXIMO E MÍNIMO
// REINICIALIZAR ESTADO INTERNO
// CONSULTAR ESTADO ATUAL
// REPRODUTIVEL QUANDO MESMA SEMENTE É UTILIZADA

#endif //GERADOR_H
